Fixed a bug in the input parsing for the CLI script

diff --git a/bin/osp_ctl b/bin/osp_ctl
--- a/bin/osp_ctl
+++ b/bin/osp_ctl
@@ -66,3 +66,5 @@ if [ ${1} == "stats" ]; then
     fi
 fi
 
+echo "Sorry, invalid command, try 'help'"
+exit 1
